# Service node port exposed to allow cluster external access to front-end wordpress http port 80

apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
spec:
  type: NodePort
  selector:
    app: wordpress
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

# Persistant volume claim for static content storage

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# Wordpress container deployment
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:php8.1-apache
        name: wordpress
        # 0,5-1 Core CPU usage, AND 512-1024Mi of RAM
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql-service
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: secret-mysql-wordpress
              key: mysql-database
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-mysql-wordpress
              key: mysql-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mysql-wordpress
              key: mysql-pass
        # Restart if no response on port tcp for 10s
        livenessProbe:
          tcpSocket:
            port: 80
          # Delay before check
          initialDelaySeconds: 10
          periodSeconds: 10
        # Do not expose service if no response within 5s
        readinessProbe:
          tcpSocket:
            port: 80
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim